name: Run Functional Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Functional Tests
    runs-on: ubuntu-latest
    services:
      test_db:
        image: postgres:16
        ports:
          - 5433:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for test_db to be ready..."
          until pg_isready -h localhost -p 5433 -U postgres; do sleep 1; done

      - name: Install migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin

      - name: Run migrations
        run: |
          migrate -path ./migrations -database "postgres://postgres:postgres@localhost:5433/testdb?sslmode=disable" up

      - name: Run tests
        run: go test ./tests -v
        env:
          DB_HOST: localhost
          DB_PORT: 5433
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: testdb
